version: '2'
services:
  nginx:
    image: "nginx-${APP_NAME}:${TAG}"
    restart: always
    depends_on:
      - php
    links:
      - php
  php:
    image: "php-${APP_NAME}:${TAG}"
    restart: always
    links:
      - redis:cache
      - db:db
    depends_on:
      - redis
      - db
  redis:
    build:
      context: ./
      dockerfile: "./${DOCKER_SOURCE_DIR}/redis/Dockerfile"
    image: "redis-${APP_NAME}:${TAG}"
    restart: always
  db:
    image: "db-${APP_NAME}:${TAG}"
    restart: always
  composer:
    image: "composer-${APP_NAME}:${TAG}"
    restart: "no"
  adminer:
    image: "adminer-${APP_NAME}:${TAG}"
    restart: always
    links:
      - db:db