version: '2'
services:
  install-project:
    build:
      context: ./
      dockerfile: "./${DOCKER_SOURCE_DIR}/composer/install/Dockerfile"
    image: "install-project-prod-${APP_NAME}:${TAG}"
    restart: 'no'
    command: install --prefer-dist --no-dev
    volumes:
      - "./${APP_DIR}:/app"