version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./source/nginx/dev/Dockerfile
    volumes:
      - "./${APP_DIR}:/app"
      - ./source/nginx/dev/conf.d:/etc/nginx/conf.d:ro
      - ./logs/dev:/var/log/nginx
    restart: always
    ports:
      - "${EXTERNAL_WEB_DEV_PORT}:80"
    env_file:
      - ./env/dev/nginx.env
  db:
    build:
      context: ./
      dockerfile: ./source/mariadb/dev/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
      - ./source/mariadb/db_dump/db_yupe:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - ./env/dev/db.env
  php:
    build:
      context: ./
      dockerfile: ./source/php/dev/Dockerfile
    volumes:
      - "./${APP_DIR}:/app"
      - ./source/php/dev/app/protected/config:/app/protected/config:rw
    restart: always
    env_file:
      - ./env/dev/php.env
  composer:
    build:
      context: ./
      dockerfile: ./source/composer/dev/Dockerfile
    restart: 'no'
    command: install --prefer-dist --dev
    volumes:
      - "./${APP_DIR}:/app"
  adminer:
    build:
      context: ./
      dockerfile: ./source/adminer/Dockerfile
    ports:
      - "${EXTERNAL_ADMINER_DEV_PORT}:80"
volumes:
  db_data:
    external: false
