version: '2'
services:
  create-project:
    build:
      context: ./
      dockerfile: "./${DOCKER_SOURCE_DIR}/composer/install/Dockerfile"
    image: "create-project-${APP_NAME}:${TAG}"
    restart: 'no'
    command: "create-project ${PACKAGE}:${BRANCH} /app/${APP_DIR} --no-install"
    volumes:
      - .:/app